name: "Publish Features and Templates"

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6

      - uses: devcontainers/action@v1
        with:
          publish-features: "true"
          publish-templates: "true"
          oci-registry: "ghcr.io"
          features-namespace: "stelonld/devcontainer-features"
          templates-namespace: "stelonld/devcontainer-templates"
          base-path-to-features: "./src"
          base-path-to-templates: "./templates"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
